libapp/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.IndexController.as_view(), name='index'),
    url(r'^books_list/$', views.BookListView.as_view(), name='books'),
    url(r'^books_list/search/$', views.SearchListView.as_view(), name='search_list_view'),
    url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    url(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
    url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
    url(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book_update'),
    url(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
    url(r'^sorry/', views.NotALinkYet.as_view(), name='sorry'),
]

library_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^libapp/', include('libapp.urls')),
    url(r'^$', RedirectView.as_view(url='/libapp/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libapp/models.py
from __future__ import unicode_literals
from django.urls import reverse

from django.db import models


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    book = models.FileField(upload_to='uploads/')
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    

libapp/forms.py
from django import forms
from libapp.models import Book, Author

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

libapp/views.py
from django.shortcuts import render
from django.views import View, generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from libapp.models import Book, Author
from . import forms
import operator


class IndexController(View):
    def get(self,request):
        num_books=Book.objects.all().count()
        num_authors=Author.objects.count()
        return render(
            request,
            'libapp/index.html',
            context={'num_books':num_books,'num_authors':num_authors},
            )

class BookListView(generic.ListView):
    model = Book
    form_class = forms.BookForm

class BookDetailView(generic.DetailView):
    model = Book
    form_class = forms.BookForm

class AuthorListView(generic.ListView):
    model = Author
    form_class = forms.AuthorForm

class AuthorDetailView(generic.DetailView):
    model = Author
    form_class = forms.AuthorForm

class AuthorCreate(CreateView):
    model = Author
    form_class = forms.AuthorForm
    success_url = reverse_lazy('authors')

class AuthorUpdate(UpdateView):
    model = Author
    form_class = forms.AuthorForm

class AuthorDelete(DeleteView):
    model = Author
    form_class = forms.BookForm
    success_url = reverse_lazy('authors')

class BookCreate(CreateView):
    model = Book
    form_class = forms.BookForm

class BookUpdate(UpdateView):
    model = Book
    form_class = forms.BookForm

class BookDelete(DeleteView):
    model = Book
    form_class = forms.BookForm
    success_url = reverse_lazy('books')


class SearchListView(generic.ListView):
    model = Book
    form_class = forms.BookForm

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Book.objects.filter(title__icontains=query)

class NotALinkYet(View):
    def get(self,request):
        return render(request,"libapp/sorry.html")
        

libapp/templates/libapp/author_confirm_delete.html
{% extends "libapp/base.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>
<br>
<form id="form" action="{% url 'authors' %}" method="get">
  <input type="submit" action="" value="No" />
</form>
{% endblock %}

libapp/templates/libapp/author_detail.html
{% extends "libapp/base.html" %}

{% block content %}
  <h1>Author: {{ author.last_name }}, {{ author.first_name }}</h1>
  
  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>
    {% if author.book_set.all%}
	
    {% for book in author.book_set.all %}
    <hr>
    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
	<br>
	<p>{{ book.summary }}</p>
    {% endfor %}
	
	{% else %}
      <p>There are no books by the author.</p>
    {% endif %}
  </div>
{% endblock %}

libapp/templates/libapp/author_form.html
{% extends "libapp/base.html"  %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table class="table">
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

libapp/templates/libapp/author_list.html
{% extends "libapp/base.html" %}

{% block content %}
    <h1>Authors</h1>

    {% if author_list %}
    <table class="table">
	
      {% for author in author_list %}
        <tr>
        <td><a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}</a></td>
        <td><a href="{% url 'author_update' author.id %}">Update</a></td>
		<td><a href="{% url 'author_delete' author.id %}">Delete</a></td>
        </tr>
	  {% endfor %}
	  
    </table>
    {% else %}
      <p>There are no authors.</p>
    {% endif %}       
{% endblock %}

libapp/templates/libapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Library</title>
	<meta charset="utf-8" />
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
	  {% load staticfiles %}
	  <link rel="stylesheet" href="{% static 'libapp/css/bootstrap.css' %}" type = "text/css"/>
	  <meta name="viewport" content = "width=device-width, initial-scale=1.0">
	
	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#f6f6f6">
	<div class="container-fluid" style="min-height:95%; ">
		<div class="row">
			  <div class="col-sm-12">
				  <br>
				  <center>
				  <h3>Welcome to my Library</h3>
				  </center>
			  </div>
		</div><hr>

		<div class="row">
		  <div class="col-sm-2">
		  <br>
		  <br>
		   <!-- Great, til you resize. -->
			<!--<div class="well bs-sidebar affix" id="sidebar" style="background-color:#fff">-->
			<div class="well bs-sidebar" id="sidebar" style="background-color:#fff">
			  {% block sidebar %}
			  <ul class="nav nav-pills nav-stacked">
				  <li><a href="{% url 'index' %}">Home</a></li>
				  <li><a href="{% url 'books' %}">All books</a></li>
				  <li><a href="{% url 'authors' %}">All authors</a></li>
				  <br> <br>
				  <li><a href="{% url 'author_create' %}">Create an author</a></li>
				  <li><a href="{% url 'book_create' %}">Create a book</a></li>
			  </ul>
			  {% endblock %}
			</div> <!--well bs-sidebar affix-->
		  </div> <!--col-sm-2-->
		  <form id="searchform" action="{% url 'search_list_view' %}" method="get" accept-charset="utf-8">
            <button class="searchbutton" type="submit">
              <i class="fa fa-search">Search</i>
            </button>
            <input class="searchfield" id="searchbox" name="q" type="text" placeholder="Type book title">
          </form>
		  <div class="col-sm-10">
			<div class='container-fluid'>
			<br><br>
			   {% block content %}
			   {% endblock %}	
			</div>
		  </div>
		</div> 
	</div>
	<footer>
		<div class="container-fluid" style='margin-left:15px'>
			<p><a href="{% url 'sorry' %}" target="blank">Contact</a> | <a href="{% url 'sorry' %}" target="blank">LinkedIn</a> | <a href="{% url 'sorry' %}" target="blank">Twitter</a> | <a href="{% url 'sorry' %}" target="blank">Google+</a></p>
		</div>
	</footer>	
	
</body>

</html>

libapp/templates/libapp/book_confirm_delete.html
{% extends "libapp/base.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book.title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>
<br>
<form id="form" action="{% url 'books' %}" method="get">
  <input type="submit" action="" value="No" />
</form>
{% endblock %}

libapp/templates/libapp/book_detail.html
{% extends "libapp/base.html" %}

{% block content %}
  {% load static %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><a href="{% static book.book %}">Open</a></p>
  

{% endblock %}

libapp/templates/libapp/book_form.html
{% extends "libapp/base.html"  %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table">
    {{ form.as_table }}
    </table>
    <input type="submit" id="submit" value="Submit" />
    
</form>
{% endblock %}

libapp/templates/libapp/book_list.html
{% extends "libapp/base.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <table class="table">

      {% for book in book_list %}
      <tr>
        <th><a href="{{ book.get_absolute_url }}">{{ book.title }}</a> 
		{%if book.author %}({{book.author}}){% else %}(unknown author){% endif %}</th>
		<th><a href="{% url 'book_update' book.id %}">Update</a></th>
		<th><a href="{% url 'book_delete' book.id %}">Delete</a></th>
      </tr>
      {% endfor %}

    </table>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

libapp/templates/libapp/index.html
{% extends "libapp/base.html" %}

{% block content %}
<h1>Library Home</h1>

  <p>Welcome to <em>my Library</em>, my test task</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

{% endblock %}

libapp/templates/libapp/sorry.html
{% extends "libapp/base.html" %}

{% block content %}
<h1>Sorry, it doesn't have a link yet, it's just for beauty</h1>
{% endblock %}